### ISSUE TITLE
Is possible in Three.js AI model Importing ?

### ISSUE THREAD

**Issue by game-jonathan** [0x088730/3D_Earth_Map_test#5]
After GPT appearance, all game engineers were develop GAME Model from image.
Also, we can integrate AI model with three.js framework?

**Comment by horizonvert1027** [comment]
Yes, it is possible in three.js + javascript framework.

By chatgpt api, we can integrate model with this.

**Comment by game-jonathan** [comment]
Thanks, I'll try it.
If I have any question, I'll ask again.
